services:
  db:
    image: postgres:16
    container_name: padel_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: padel_booking
    ports:
      - "5432:5432"
    volumes:
      - padel_booking_pgdata:/var/lib/postgresql/data

volumes:
  padel_booking_pgdata:
